import { HttpStatus } from '@nestjs/common';

/**
 * 화면·API 정의서 15장 오류 코드. 업무 오류는 반드시 이 목록에 등록해 사용한다.
 */
export const ERROR_CODES = {
  // 공통
  VALIDATION_ERROR: HttpStatus.BAD_REQUEST,
  AUTH_REQUIRED: HttpStatus.UNAUTHORIZED,
  AUTH_INVALID_CREDENTIALS: HttpStatus.UNAUTHORIZED,
  AUTH_ACCOUNT_LOCKED: HttpStatus.UNAUTHORIZED,
  AUTH_ACCOUNT_INACTIVE: HttpStatus.UNAUTHORIZED,
  AUTH_REFRESH_INVALID: HttpStatus.UNAUTHORIZED,
  PERMISSION_DENIED: HttpStatus.FORBIDDEN,
  NOT_FOUND: HttpStatus.NOT_FOUND,
  VERSION_CONFLICT: HttpStatus.CONFLICT,
  INVALID_STATUS_TRANSITION: HttpStatus.CONFLICT,
  RATE_LIMITED: HttpStatus.TOO_MANY_REQUESTS,
  INTERNAL_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,

  // 고객·예약
  CUSTOMER_NOT_FOUND: HttpStatus.NOT_FOUND,
  CUSTOMER_PHONE_DUPLICATE: HttpStatus.CONFLICT,
  NAVER_RESERVATION_CONFLICT: HttpStatus.CONFLICT,

  // 계약·주문
  CONTRACT_NOT_DRAFT: HttpStatus.CONFLICT,
  CONTRACT_VERSION_CONFLICT: HttpStatus.CONFLICT,
  ORDER_ITEM_COUNT_LOCKED: HttpStatus.UNPROCESSABLE_ENTITY,

  // 옵션·채촌·작업지시서
  OPTION_SET_INVALID: HttpStatus.UNPROCESSABLE_ENTITY,
  OPTION_STAGE_INCOMPLETE: HttpStatus.UNPROCESSABLE_ENTITY,
  MEASUREMENT_NOT_COMPLETE: HttpStatus.UNPROCESSABLE_ENTITY,
  /** 작업지시서 출력 근거로 쓰인 채촌의 수정·삭제·완료해제 (설계서 09 §2.1) */
  MEASUREMENT_LOCKED: HttpStatus.CONFLICT,
  WORK_ORDER_PREREQUISITE_MISSING: HttpStatus.UNPROCESSABLE_ENTITY,

  // 렌탈
  RENTAL_PERIOD_OVERLAP: HttpStatus.CONFLICT,
  RENTAL_ITEM_NOT_AVAILABLE: HttpStatus.CONFLICT,
  RENTAL_ID_MISMATCH: HttpStatus.CONFLICT,

  // 파일
  FILE_TYPE_NOT_ALLOWED: HttpStatus.BAD_REQUEST,
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
